language: cpp
before_script:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script: g++-4.8 -fstack-protector-strong -Wl,-O1 -O0 -pipe -fPIC -g3 -o tinyirc main.cpp -std=c++11 -lpthread
